#!/bin/bash
# =============================================================
#  Create Delight Remake — Docker 容器入口脚本
#  功能：
#    1. 将只读的服务端资产软链接/复制到 /data（可写卷）
#    2. 处理 EULA 同意
#    3. 生成 server.properties（支持环境变量覆盖）
#    4. 写入 JVM 参数
#    5. 启动 Forge 服务器
# =============================================================

set -eo pipefail

# ── 颜色输出 ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RESET='\033[0m'
info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

# ── 打印 Banner ──
cat <<'EOF'
  ____                _         ____       _ _       _     _   
 / ___|_ __ ___  __ _| |_ ___  |  _ \  ___| (_) __ _| |__ | |_ 
| |   | '__/ _ \/ _` | __/ _ \ | | | |/ _ \ | |/ _` | '_ \| __|
| |___| | |  __/ (_| | ||  __/ | |_| |  __/ | | (_| | | | | |_ 
 \____|_|  \___|\__,_|\__\___| |____/ \___|_|_|\__, |_| |_|\__|
                                                |___/           
  Remake v0.4.7.14  |  Minecraft 1.20.1  |  Forge 47.4.10
EOF

# ── 环境变量（均可被外部覆盖）──────────────────────────────

# JVM 内存
: "${MEMORY_INIT:=4G}"
: "${MEMORY_MAX:=6G}"

# 额外 JVM 参数（追加到默认 G1GC 参数后）
: "${JVM_OPTS:=}"

# 完整 JVM 参数（若设置则完全覆盖默认值）
: "${JVM_ARGS:=}"

# EULA：设为 TRUE 代表接受 https://account.mojang.com/documents/minecraft_eula
: "${EULA:=FALSE}"

# ── server.properties 可配置项 ──
: "${SERVER_NAME:=Create Delight Remake}"
: "${MOTD:=${SERVER_NAME}}"
: "${MAX_PLAYERS:=20}"
: "${DIFFICULTY:=normal}"
: "${GAMEMODE:=survival}"
: "${FORCE_GAMEMODE:=false}"
: "${HARDCORE:=false}"
: "${PVP:=true}"
: "${ALLOW_NETHER:=true}"
: "${ONLINE_MODE:=true}"
: "${WHITE_LIST:=false}"
: "${SPAWN_PROTECTION:=16}"
: "${MAX_WORLD_SIZE:=29999984}"
: "${VIEW_DISTANCE:=10}"
: "${SIMULATION_DISTANCE:=10}"
: "${LEVEL_TYPE:=minecraft:default}"
: "${LEVEL_SEED:=}"
: "${LEVEL_NAME:=world}"
: "${SERVER_PORT:=25565}"
: "${RCON_ENABLED:=false}"
: "${RCON_PORT:=25575}"
: "${RCON_PASSWORD:=}"
: "${ENABLE_COMMAND_BLOCK:=false}"
: "${MAX_TICK_TIME:=60000}"
: "${NETWORK_COMPRESSION_THRESHOLD:=256}"
: "${RATE_LIMIT:=0}"
: "${SPAWN_ANIMALS:=true}"
: "${SPAWN_MONSTERS:=true}"
: "${SPAWN_NPCS:=true}"
: "${OP_PERMISSION_LEVEL:=4}"
: "${FUNCTION_PERMISSION_LEVEL:=2}"
: "${LOG_IPS:=true}"

# ── 目录定义 ──
SERVER_DIR="/server"   # 只读资产
DATA_DIR="/data"       # 可写卷

# =============================================================
#  步骤 1：将只读资产链接到 /data（如果 /data 中不存在）
# =============================================================
info "Preparing /data directory from server assets..."

# 需要软链接到数据卷的"运行时生成"目录
RUNTIME_DIRS=(world logs crash-reports)
for d in "${RUNTIME_DIRS[@]}"; do
    mkdir -p "${DATA_DIR}/${d}"
    if [ ! -L "${SERVER_DIR}/${d}" ] && [ ! -d "${SERVER_DIR}/${d}" ]; then
        ln -sf "${DATA_DIR}/${d}" "${SERVER_DIR}/${d}"
    fi
done

# 运行时生成的文件（通过软链接使其落入 /data）
RUNTIME_FILES=(banned-ips.json banned-players.json ops.json whitelist.json usercache.json)
for f in "${RUNTIME_FILES[@]}"; do
    touch "${DATA_DIR}/${f}" 2>/dev/null || true
    if [ ! -L "${SERVER_DIR}/${f}" ]; then
        ln -sf "${DATA_DIR}/${f}" "${SERVER_DIR}/${f}"
    fi
done

success "Asset linking complete."

# =============================================================
#  步骤 2：EULA 检查
# =============================================================
EULA_FILE="${DATA_DIR}/eula.txt"

if [[ "${EULA^^}" == "TRUE" ]]; then
    if ! grep -q "eula=true" "${EULA_FILE}" 2>/dev/null; then
        info "Writing eula.txt (EULA=TRUE accepted)..."
        cat > "${EULA_FILE}" <<EOF
# By setting eula=true you are indicating your agreement to Minecraft's EULA:
# https://account.mojang.com/documents/minecraft_eula
eula=true
EOF
    fi
    # 软链接到服务器目录
    ln -sf "${EULA_FILE}" "${SERVER_DIR}/eula.txt" 2>/dev/null || true
    success "EULA accepted."
else
    error "You must accept the Minecraft EULA by setting environment variable EULA=TRUE
       https://account.mojang.com/documents/minecraft_eula"
fi

# =============================================================
#  步骤 3：生成 server.properties（仅首次，之后可手动编辑）
# =============================================================
PROPS_FILE="${DATA_DIR}/server.properties"

if [ ! -f "${PROPS_FILE}" ]; then
    info "Generating server.properties..."
    cat > "${PROPS_FILE}" <<EOF
# Minecraft server properties
# Generated by Create Delight Remake Docker entrypoint
# Edit this file and restart the container to apply changes.

server-port=${SERVER_PORT}
motd=${MOTD}
max-players=${MAX_PLAYERS}
difficulty=${DIFFICULTY}
gamemode=${GAMEMODE}
force-gamemode=${FORCE_GAMEMODE}
hardcore=${HARDCORE}
pvp=${PVP}
allow-nether=${ALLOW_NETHER}
online-mode=${ONLINE_MODE}
white-list=${WHITE_LIST}
spawn-protection=${SPAWN_PROTECTION}
max-world-size=${MAX_WORLD_SIZE}
view-distance=${VIEW_DISTANCE}
simulation-distance=${SIMULATION_DISTANCE}
level-type=${LEVEL_TYPE}
level-seed=${LEVEL_SEED}
level-name=${LEVEL_NAME}
enable-rcon=${RCON_ENABLED}
rcon.port=${RCON_PORT}
rcon.password=${RCON_PASSWORD}
enable-command-block=${ENABLE_COMMAND_BLOCK}
max-tick-time=${MAX_TICK_TIME}
network-compression-threshold=${NETWORK_COMPRESSION_THRESHOLD}
rate-limit=${RATE_LIMIT}
spawn-animals=${SPAWN_ANIMALS}
spawn-monsters=${SPAWN_MONSTERS}
spawn-npcs=${SPAWN_NPCS}
op-permission-level=${OP_PERMISSION_LEVEL}
function-permission-level=${FUNCTION_PERMISSION_LEVEL}
log-ips=${LOG_IPS}
resource-pack=
require-resource-pack=false
enforce-whitelist=false
sync-chunk-writes=true
enable-jmx-monitoring=false
EOF
    success "server.properties generated."
else
    info "server.properties already exists, skipping generation."
fi

# 软链接到服务器目录
ln -sf "${PROPS_FILE}" "${SERVER_DIR}/server.properties" 2>/dev/null || true

# =============================================================
#  步骤 4：写入 JVM 参数
# =============================================================
JVM_ARGS_FILE="${SERVER_DIR}/user_jvm_args.txt"

if [ -n "${JVM_ARGS}" ]; then
    # 完整覆盖模式
    echo "${JVM_ARGS}" > "${JVM_ARGS_FILE}"
    info "user_jvm_args.txt written (full override mode)."
else
    # 默认 G1GC 优化参数 + 用户追加
    cat > "${JVM_ARGS_FILE}" <<EOF
-Xms${MEMORY_INIT}
-Xmx${MEMORY_MAX}
-XX:+UnlockExperimentalVMOptions
-XX:+AlwaysPreTouch
-XX:+UseG1GC
-XX:InitiatingHeapOccupancyPercent=70
-XX:-G1UseAdaptiveIHOP
-XX:G1NewSizePercent=40
-XX:G1MaxNewSizePercent=50
-XX:MaxTenuringThreshold=15
-XX:SurvivorRatio=6
-XX:G1MixedGCLiveThresholdPercent=60
-XX:G1MixedGCCountTarget=6
-XX:ThreadPriorityPolicy=0
${JVM_OPTS}
EOF
    info "user_jvm_args.txt written (Xms=${MEMORY_INIT} Xmx=${MEMORY_MAX})."
fi

# =============================================================
#  步骤 5：启动服务器
# =============================================================
cd "${SERVER_DIR}"
chmod +x run.sh

success "All checks passed. Starting Create Delight Remake server..."
echo "──────────────────────────────────────────────────"
echo "  Port          : ${SERVER_PORT}"
echo "  Max Players   : ${MAX_PLAYERS}"
echo "  Online Mode   : ${ONLINE_MODE}"
echo "  RCON          : ${RCON_ENABLED} (port ${RCON_PORT})"
echo "  Memory        : ${MEMORY_INIT} ~ ${MEMORY_MAX}"
echo "──────────────────────────────────────────────────"

# exec 让 run.sh 成为 PID 1 的子进程，tini 负责信号转发
exec ./run.sh nogui "$@"
